# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
defaults:
   run:
    working-directory: taudinpurkauspeli/frontend

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          persist-credentials: false
      
    - name: Reconfigure git to use HTTP authentication
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      
    - name: e2e tests
      uses: cypress-io/github-action@v2
      with:
        build: npm run build
        start: npm start

    - name: Build
      run: npm run build

    - name: Copy front to back
      run: cp -r build ../backend/build
